// default package
// Generated 11-Jun-2012 16:41:24 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Outcome generated by hbm2java
 */
public class Outcome  implements java.io.Serializable {


     private OutcomeId id;
     private String reviewReason;
     private String userExperience;
     private String otherEvidence;
     private String outcomeStatementId;
     private String judgementStatementId;
     private String judgementSummary;
     private String method;
     private String inspectionTheme;
     private String judgementReason;
     private String complianceLevel;
     private Character inspectionAnnounced;
     private String source;
     private Character actionCode;
     private Date lastUpdated;

    public Outcome() {
    }

	
    public Outcome(OutcomeId id) {
        this.id = id;
    }
    public Outcome(OutcomeId id, String reviewReason, String userExperience, String otherEvidence, String outcomeStatementId, String judgementStatementId, String judgementSummary, String method, String inspectionTheme, String judgementReason, String complianceLevel, Character inspectionAnnounced, String source, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.reviewReason = reviewReason;
       this.userExperience = userExperience;
       this.otherEvidence = otherEvidence;
       this.outcomeStatementId = outcomeStatementId;
       this.judgementStatementId = judgementStatementId;
       this.judgementSummary = judgementSummary;
       this.method = method;
       this.inspectionTheme = inspectionTheme;
       this.judgementReason = judgementReason;
       this.complianceLevel = complianceLevel;
       this.inspectionAnnounced = inspectionAnnounced;
       this.source = source;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public OutcomeId getId() {
        return this.id;
    }
    
    public void setId(OutcomeId id) {
        this.id = id;
    }
    public String getReviewReason() {
        return this.reviewReason;
    }
    
    public void setReviewReason(String reviewReason) {
        this.reviewReason = reviewReason;
    }
    public String getUserExperience() {
        return this.userExperience;
    }
    
    public void setUserExperience(String userExperience) {
        this.userExperience = userExperience;
    }
    public String getOtherEvidence() {
        return this.otherEvidence;
    }
    
    public void setOtherEvidence(String otherEvidence) {
        this.otherEvidence = otherEvidence;
    }
    public String getOutcomeStatementId() {
        return this.outcomeStatementId;
    }
    
    public void setOutcomeStatementId(String outcomeStatementId) {
        this.outcomeStatementId = outcomeStatementId;
    }
    public String getJudgementStatementId() {
        return this.judgementStatementId;
    }
    
    public void setJudgementStatementId(String judgementStatementId) {
        this.judgementStatementId = judgementStatementId;
    }
    public String getJudgementSummary() {
        return this.judgementSummary;
    }
    
    public void setJudgementSummary(String judgementSummary) {
        this.judgementSummary = judgementSummary;
    }
    public String getMethod() {
        return this.method;
    }
    
    public void setMethod(String method) {
        this.method = method;
    }
    public String getInspectionTheme() {
        return this.inspectionTheme;
    }
    
    public void setInspectionTheme(String inspectionTheme) {
        this.inspectionTheme = inspectionTheme;
    }
    public String getJudgementReason() {
        return this.judgementReason;
    }
    
    public void setJudgementReason(String judgementReason) {
        this.judgementReason = judgementReason;
    }
    public String getComplianceLevel() {
        return this.complianceLevel;
    }
    
    public void setComplianceLevel(String complianceLevel) {
        this.complianceLevel = complianceLevel;
    }
    public Character getInspectionAnnounced() {
        return this.inspectionAnnounced;
    }
    
    public void setInspectionAnnounced(Character inspectionAnnounced) {
        this.inspectionAnnounced = inspectionAnnounced;
    }
    public String getSource() {
        return this.source;
    }
    
    public void setSource(String source) {
        this.source = source;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


