// default package
// Generated 11-Jun-2012 16:41:24 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * ReportSummary generated by hbm2java
 */
public class ReportSummary  implements java.io.Serializable {


     private ReportSummaryId id;
     private String text;
     private Character actionCode;
     private Date lastUpdated;

    public ReportSummary() {
    }

	
    public ReportSummary(ReportSummaryId id) {
        this.id = id;
    }
    public ReportSummary(ReportSummaryId id, String text, Character actionCode, Date lastUpdated) {
       this.id = id;
       this.text = text;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public ReportSummaryId getId() {
        return this.id;
    }
    
    public void setId(ReportSummaryId id) {
        this.id = id;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


