//package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Location_Condition generated by hbm2java
 */
public class Location_Condition  implements java.io.Serializable {

    private String providerId;
    private String locationId;
    private String conditionId;
    private String regulatedActivityNumber;
     private Character type;
     private String text;
     private String reason;
     private Character actionCode;
     private Date lastUpdated;

    public Location_Condition() {
    }

    public Location_Condition(String providerId, String locationId, String conditionId, String regulatedActivityNumber) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.conditionId = conditionId;
       this.regulatedActivityNumber = regulatedActivityNumber;
    }

    public Location_Condition(String providerId, String locationId, String conditionId, String regulatedActivityNumber, Character type, String text, String reason, Character actionCode, Date lastUpdated) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.conditionId = conditionId;
       this.regulatedActivityNumber = regulatedActivityNumber;
       this.type = type;
       this.text = text;
       this.reason = reason;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
 
    public String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    public String getLocationId() {
        return this.locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    public String getConditionId() {
        return this.conditionId;
    }

    public void setConditionId(String conditionId) {
        this.conditionId = conditionId;
    }

    public String getRegulatedActivityNumber() {
        return this.regulatedActivityNumber;
    }

    public void setRegulatedActivityNumber(String regulatedActivityNumber) {
        this.regulatedActivityNumber = regulatedActivityNumber;
    }
 
    public Character getType() {
        return this.type;
    }
    
    public void setType(Character type) {
        this.type = type;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


