//package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * NominatedIndividual generated by hbm2java
 */
public class Nominated_Individual  implements java.io.Serializable {

     private String providerId;
     private String regulatedActivityNumber;
     private String name;
     private Character actionCode;
     private Date lastUpdated;

    public Nominated_Individual() {
    }
	
    public Nominated_Individual(String regulatedActivityNumber) {
        this.regulatedActivityNumber = regulatedActivityNumber; 
    }

    public Nominated_Individual(String providerId, String regulatedActivityNumber, String name, Character actionCode, Date lastUpdated) {
       this.providerId = providerId;
       this.regulatedActivityNumber = regulatedActivityNumber;
       this.name = name;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    public String getRegulatedActivityNumber() {
        return this.regulatedActivityNumber;
    }

    public void setRegulatedActivityNumber(String regulatedActivityNumber) {
        this.regulatedActivityNumber = regulatedActivityNumber;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


