//package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Outcome generated by hbm2java
 */
public class Outcome  implements java.io.Serializable {

    private String providerId;
    private String locationId;
    private String outcomeId;
     private String judgementId;
     private String judgementDate;
     private String judgementReason;
     private String judgementUserExperience;
     private String judgementOtherEvidence;
     private String judgementScoreId;
     private String outcomeStatementId;
     private String judgementSummary;
     private Character actionCode;
     private Date lastUpdated;

    public Outcome() {
    }
	
    public Outcome(String providerId, String locationId, String outcomeId) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.outcomeId = outcomeId;
    }

    public Outcome(String providerId, String locationId, String outcomeId, String judgementId, String judgementDate, String judgementReason, String judgementUserExperience, String judgementOtherEvidence, String judgementScoreId, String outcomeStatementId, String judgementSummary, Character actionCode, Date lastUpdated) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.outcomeId = outcomeId;
       this.judgementId = judgementId;
       this.judgementDate = judgementDate;
       this.judgementReason = judgementReason;
       this.judgementUserExperience = judgementUserExperience;
       this.judgementOtherEvidence = judgementOtherEvidence;
       this.judgementScoreId = judgementScoreId;
       this.outcomeStatementId = outcomeStatementId;
       this.judgementSummary = judgementSummary;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
 
    public String getProviderId() {
        return this.providerId;
    }
 
    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    public String getLocationId() {
        return this.locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    public String getOutcomeId() {
        return this.outcomeId;
    }

    public void setOutcomeId(String outcomeId) {
        this.outcomeId = outcomeId;
    } 

    public String getJudgementId() {
        return this.judgementId;
    }
    
    public void setJudgementId(String judgementId) {
        this.judgementId = judgementId;
    }
    public String getJudgementDate() {
        return this.judgementDate;
    }
    
    public void setJudgementDate(String judgementDate) {
        this.judgementDate = judgementDate;
    }
    public String getJudgementReason() {
        return this.judgementReason;
    }
    
    public void setJudgementReason(String judgementReason) {
        this.judgementReason = judgementReason;
    }
    public String getJudgementUserExperience() {
        return this.judgementUserExperience;
    }
    
    public void setJudgementUserExperience(String judgementUserExperience) {
        this.judgementUserExperience = judgementUserExperience;
    }
    public String getJudgementOtherEvidence() {
        return this.judgementOtherEvidence;
    }
    
    public void setJudgementOtherEvidence(String judgementOtherEvidence) {
        this.judgementOtherEvidence = judgementOtherEvidence;
    }
    public String getJudgementScoreId() {
        return this.judgementScoreId;
    }
    
    public void setJudgementScoreId(String judgementScoreId) {
        this.judgementScoreId = judgementScoreId;
    }
    public String getOutcomeStatementId() {
        return this.outcomeStatementId;
    }
    
    public void setOutcomeStatementId(String outcomeStatementId) {
        this.outcomeStatementId = outcomeStatementId;
    }
    public String getJudgementSummary() {
        return this.judgementSummary;
    }
    
    public void setJudgementSummary(String judgementSummary) {
        this.judgementSummary = judgementSummary;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


