//package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Provider_Regulated_Activity generated by hbm2java
 */
public class Provider_Regulated_Activity  implements java.io.Serializable, CQC_Entity {

     private String providerId;
     private String regulatedActivityNumber;
     private Character actionCode;
     private Date lastUpdated;

    public Provider_Regulated_Activity() {
    }

    public Provider_Regulated_Activity(String providerId, String regulatedActivityNumber) {
        this.providerId = providerId;
        this.regulatedActivityNumber = regulatedActivityNumber;
    }
    public Provider_Regulated_Activity(String providerId, String regulatedActivityNumber, Character actionCode, Date lastUpdated) {
       this.providerId = providerId;
       this.regulatedActivityNumber = regulatedActivityNumber;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
  
    public String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    public String getRegulatedActivityNumber() {
        return this.regulatedActivityNumber;
    }

    public void setRegulatedActivityNumber(String regulatedActivityNumber) {
        this.regulatedActivityNumber = regulatedActivityNumber;
    }
 
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }

    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
                 if ( (other == null ) ) return false;
                 if ( !(other instanceof Provider_Regulated_Activity) ) return false;
                 Provider_Regulated_Activity castOther = (Provider_Regulated_Activity) other;

                 return ( (this.getProviderId()==castOther.getProviderId()) || ( this.getProviderId()!=null && castOther.getProviderId()!=null && this.getProviderId().equals(castOther.getProviderId()) ) )
 && ( (this.getRegulatedActivityNumber()==castOther.getRegulatedActivityNumber()) || ( this.getRegulatedActivityNumber()!=null && castOther.getRegulatedActivityNumber()!=null && this.getRegulatedActivityNumber().equals(castOther.getRegulatedActivityNumber()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getProviderId() == null ? 0 : this.getProviderId().hashCode() );
         result = 37 * result + ( getRegulatedActivityNumber() == null ? 0 : this.getRegulatedActivityNumber().hashCode() );
         return result;
   }

   public String getPK() {
         return String.format("%s/%s", getProviderId(), 
                                          getRegulatedActivityNumber());
   }

}


