//package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Provider_Condition generated by hbm2java
 */
public class Provider_Condition  implements java.io.Serializable {

     private String providerId;
     private String conditionId;
     private String regulatedActivityNumber;
     private String text;
     private String reason;
     private Character actionCode;
     private Date lastUpdated;

    public Provider_Condition() {
    }
	
    public Provider_Condition(String providerId, String regulatedActivityNumber) {
        this.providerId = providerId;
        this.regulatedActivityNumber = regulatedActivityNumber;
    }
    public Provider_Condition(String providerId, String conditionId, String regulatedActivityNumber, String text, String reason, Character actionCode, Date lastUpdated) {
       this.providerId = providerId;
       this.conditionId = conditionId;
       this.regulatedActivityNumber = regulatedActivityNumber;
       this.text = text;
       this.reason = reason;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
  
    public String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }

    public String getConditionId() {
        return this.conditionId;
    }

    public void setConditionId(String conditionId) {
        this.conditionId = conditionId;
    }
 
    public String getRegulatedActivityNumber() {
        return this.regulatedActivityNumber;
    }
    
    public void setRegulatedActivityNumber(String regulatedActivityNumber) {
        this.regulatedActivityNumber = regulatedActivityNumber;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }




}


