//package org.cqc;
// Generated 24-May-2012 12:01:54 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Report_Summary generated by hbm2java
 */
public class Report_Summary  implements java.io.Serializable, CQC_Entity {

     private String providerId;
     private String locationId;
     private String reportPublicationDate;
     private String text;
     private Character actionCode;
     private Date lastUpdated;

    public Report_Summary() {
    }

    public Report_Summary(String providerId, String locationId, String reportPublicationDate) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.reportPublicationDate = reportPublicationDate;
    }
	
    public Report_Summary(String providerId, String locationId, String reportPublicationDate, String text, Character actionCode, Date lastUpdated) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.reportPublicationDate = reportPublicationDate;
       this.text = text;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
  
   public String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getLocationId() {
        return this.locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }
 
    public String getReportPublicationDate() {
        return this.reportPublicationDate;
    }
    
    public void setReportPublicationDate(String reportPublicationDate) {
        this.reportPublicationDate = reportPublicationDate;
    }

    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
                 if ( (other == null ) ) return false;
                 if ( !(other instanceof Report_Summary) ) return false;
                 Report_Summary castOther = ( Report_Summary ) other;

return ( (this.getProviderId()==castOther.getProviderId()) || ( this.getProviderId()!=null && castOther.getProviderId()!=null && this.getProviderId().equals(castOther.getProviderId()) ) )
    && ( (this.getLocationId()==castOther.getLocationId()) || ( this.getLocationId()!=null && castOther.getLocationId()!=null && this.getLocationId().equals(castOther.getLocationId()) ) )
    && ( (this.getReportPublicationDate()==castOther.getReportPublicationDate()) || ( this.getReportPublicationDate()!=null && castOther.getReportPublicationDate()!=null && this.getReportPublicationDate().equals(castOther.getReportPublicationDate()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getProviderId() == null ? 0 : this.getProviderId().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         result = 37 * result + ( getReportPublicationDate() == null ? 0 : this.getReportPublicationDate().hashCode() );
         return result;
   }

   public String getPK() {
         return String.format("%s/%s/%s", getProviderId(), getLocationId(), getReportPublicationDate());
   }


}


