// default package
// Generated 11-Jun-2012 16:41:24 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Service_Type generated by hbm2java
 */
public class Service_Type  implements java.io.Serializable {

     private String providerId;
     private String locationId;
     private String serviceTypeId;
     private Character actionCode;
     private Date lastUpdated;

    public Service_Type() {
    }

    public Service_Type(String providerId, String locationId, String serviceTypeId) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.serviceTypeId = serviceTypeId;
    }

    public Service_Type(String providerId, String locationId, String serviceTypeId, Character actionCode, Date lastUpdated) {
       this.providerId = providerId;
       this.locationId = locationId;
       this.serviceTypeId = serviceTypeId;
       this.actionCode = actionCode;
       this.lastUpdated = lastUpdated;
    }
   
    public String getProviderId() {
        return this.providerId;
    }

    public void setProviderId(String providerId) {
        this.providerId = providerId;
    }
    public String getLocationId() {
        return this.locationId;
    }

    public void setLocationId(String locationId) {
        this.locationId = locationId;
    }

    public String getServiceTypeId() {
        return this.serviceTypeId;
    }

    public void setServiceTypeId(String serviceTypeId) {
        this.serviceTypeId = serviceTypeId;
    }

    public Character getActionCode() {
        return this.actionCode;
    }
    
    public void setActionCode(Character actionCode) {
        this.actionCode = actionCode;
    }
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
                 if ( (other == null ) ) return false;
                 if ( !(other instanceof Service_Type) ) return false;
                 Service_Type castOther = ( Service_Type ) other;

                 return ( (this.getProviderId()==castOther.getProviderId()) || ( this.getProviderId()!=null && castOther.getProviderId()!=null && this.getProviderId().equals(castOther.getProviderId()) ) )
 && ( (this.getLocationId()==castOther.getLocationId()) || ( this.getLocationId()!=null && castOther.getLocationId()!=null && this.getLocationId().equals(castOther.getLocationId()) ) )
 && ( (this.getServiceTypeId()==castOther.getServiceTypeId()) || ( this.getServiceTypeId()!=null && castOther.getServiceTypeId()!=null && this.getServiceTypeId().equals(castOther.getServiceTypeId()) ) );
   }

   public int hashCode() {
         int result = 17;

         result = 37 * result + ( getProviderId() == null ? 0 : this.getProviderId().hashCode() );
         result = 37 * result + ( getLocationId() == null ? 0 : this.getLocationId().hashCode() );
         result = 37 * result + ( getServiceTypeId() == null ? 0 : this.getServiceTypeId().hashCode() );
         return result;
   }



}


